# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Katherine Elizabeth Anne Wolffe
tagline:          'I think passion is contagious, and interest is palpable. As a reporter, my curiosity is never satiated.'
description:      'Journalist, Creative Writer & UC Berkeley student'
url:              http://www.katewolffe.com
baseurl:          http://www.katewolffe.com

# Social Media Content
email: katewolffe@gmail.com
twitter_username: katewolffe
linkedin_username: kate-wolffe

# Dependencies:
gems:
  - jekyll-gist
